/*
 * Recyclapp - Projet de session GLO-2004, A2014
 * Equipe Engrenages
 * Alexandre Poli * Clement Sanquer * Gabriel Grenon * Martin Boisvert
 */

package recyclapp.view;

import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import recyclapp.model.Controller;
import recyclapp.transport.MaterialFlowTable;
import recyclapp.transport.MaterialFlow;

/**
 *
 * @author Martin Boisvert
 */
public class SelectedPropertiesPanel extends JPanel {
    private static SelectedPropertiesPanel sInstance;
    
    private static final String UNSELECTED_TEXT = "<No selection>";
    
    /**
     * Creates new form SelectedPropertiesPanel
     */
    @Deprecated
    public SelectedPropertiesPanel() {
        initComponents();
    }
    
    public static SelectedPropertiesPanel getInstance() {
        if (sInstance == null) {
            sInstance = new SelectedPropertiesPanel();
        }
        return sInstance;
    }
    
    public void setSelection(DiagramObject selected) {
        DefaultTableModel table = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String name = UNSELECTED_TEXT;
        MaterialFlowTable throughput = null;
        
        if (selected instanceof ElementView) {
            ElementView element = (ElementView) selected;
            name = Controller.getInstance().getElementName(element.getID()) + " <" +
                   Controller.getInstance().getElementType(element.getID()) + '>';
            
            throughput = Controller.getInstance().getThroughput(element.getID());
        }
        else if (selected instanceof NodeView) {
            NodeView node = (NodeView) selected;
            if (node.aNodeType == NodeView.ENTRY_NODE) {
                name = Controller.getInstance().getEntryNodeName(node.getParentId(), node.getIndex());
                throughput = Controller.getInstance().getEntryNodeThroughput(node.getParentId(), node.getIndex());
            }
            else if (node.aNodeType == NodeView.EXIT_NODE) {
                name = Controller.getInstance().getExitNodeName(node.getParentId(), node.getIndex());
                throughput = Controller.getInstance().getExitNodeThroughput(node.getParentId(), node.getIndex());
            }
        }
        else if (selected instanceof ConveyorView) {
            // A conveyor's throughput is always its entrynode's throughput
            ConveyorView conveyor = (ConveyorView) selected;
            NodeView node = conveyor.aEntry;
            name = Controller.getInstance().getConveyorName(node.getParentId(), node.getIndex());
            throughput = Controller.getInstance().getEntryNodeThroughput(node.getParentId(), node.getIndex());
        }
        
        if (throughput != null) {
            Vector<String> materials =  new Vector<>();
            Vector<Float> flows =  new Vector<>();
            for (MaterialFlow mat : throughput) {
                materials.add(mat.aName);
                flows.add(mat.aFlow);
            }
            Vector<Vector> tableData = new Vector<>();
            tableData.add(flows);
            table.setDataVector(tableData, materials);
        }
        jThroughputTable.setModel(table);
        jSelectedElementName.setText(name);
    }
    
    public void clearSelection() {
        jThroughputTable.setModel(new DefaultTableModel());
        jSelectedElementName.setText(UNSELECTED_TEXT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSelectedElementName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jThroughputTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jSelectedElementName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSelectedElementName.setText("<No selection>");

        jThroughputTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jThroughputTable);

        jLabel1.setText("Throughput");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSelectedElementName, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSelectedElementName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSelectedElementName;
    private javax.swing.JTable jThroughputTable;
    // End of variables declaration//GEN-END:variables
}
